### ISSUE TITLE
Set up Google Analytics

### ISSUE THREAD

**Issue by Shreyanand** [AICoE/meteor#50]
For issue #18, set up google analytics dashboard for the Meteor Webpage. Once it is available, we will customize the dashboard to reflect our requirements.

To do:
- Integrate Google Analytics account (currently using OF account) into test JupyterBook
- Track GA metrics in a shareable dashboard

Acceptance

- [X] Link to Google Analytics dashboard

**Comment by Shreyanand** [comment]
@tumido How much is this demo associated with or dependent on the Operate First world? Asking so that we can figure out if we need a new google analytics account for this or if we can reuse the OF account.

**Comment by tumido** [comment]
@Shreyanand the demo is fully independent and can be hosted anywhere, however we plan to deploy it to Operate First so for now we can reuse op1st account. If we're integrating Google Analytics, we have to make it configurable going forward anyways, so... right now, let's not worry about which account to use and use what we have available - op1st account . :slightly_smiling_face:

**Comment by hemajv** [comment]
We have setup a Google Analytics account for Project Meteor purposes and tried configuring it with one of our fork of the Elyra tutorial. However, we ran into an issue of the new Google Analytics tracking ID not being compatible for tracking JupyterBook hosted websites. This issue seems to be discussed [here](https://github.com/executablebooks/jupyter-book/issues/1300). It appears to be fixed in Sphinx [here](https://github.com/pydata/pydata-sphinx-theme/issues/385), but not yet reflected in JupyterBook.

**Comment by Shreyanand** [comment]
I was able to get it working at my fork. It can be seen [here](https://shreyanand.github.io/elyra-aidevsecops-tutorial/README.html).

If you clicked on it, we'll know :rofl:

**Comment by hemajv** [comment]
We have a dashboard available here: https://datastudio.google.com/reporting/5115a591-f004-4e5f-88e2-d38cc2d26561 
(the data is being collected from Shrey's fork of the Elyra tutorial)
