### ISSUE TITLE
Setup Prometheus for Metrics

### ISSUE THREAD

**Issue by aakankshaduggal** [AICoE/meteor#51]
For issue #18, we would need to configure Prometheus for scraping the Meteor application. Once this is setup, we can look into having the metrics defined in #17, #58 be available in Prometheus.

**Acceptance Criteria**

We will need to setup metrics for:

- [x] Meteor web application: http://meteor-shower-aicoe-meteor.apps.zero.massopen.cloud/
- [x] Meteor operator
- [x] Pipelines (Tekton build pipelines)
- [x] Pipeline Operations such as # tag releases, avg tag release time etc by setting up Pushgateway

**Comment by hemajv** [comment]
It seems like the meteor app itself does not expose any metrics at the moment, i.e. there is no `/metrics` endpoint available for Prometheus to scrape metrics from. We will need to look into exposing metrics for the meteor app deployed here: http://meteor-shower-aicoe-meteor.apps.zero.massopen.cloud/

**Comment by hemajv** [comment]
After discussing with @harshad16 it looks like the metrics can be configured for the different components as follows:

1. **Meteor web application/service** - We will need to expose a `/metrics` endpoint for the web service
2. **Meteor operator** - We will need to expose a `/metrics` endpoint for the meteor operator
3. **Pipeline** - Since we are using Tekton pipelines and it is part of OpenShift pipelines, openshift monitoring exposes Tekton metrics like: https://tekton.dev/docs/pipelines/metrics/ that we can expose for our pipelines
4. **Pipeline operations** - Operations such image tag release, how many successful tag releases we had, time taken for a tag release etc. These image/release operations are contained inside a bash script, so we will need to:
define custom prometheus metrics inside this bash script -> push these metrics to a pushgateway -> add this pushgateway as an endpoint for prometheus

**Comment by hemajv** [comment]
Thanks to @tumido @4n4nd for all your help! :heart: 

We now have metrics for:

1. **Meteor web app**: https://prometheus-portal-opf-monitoring.apps.zero.massopen.cloud/graph?g0.expr=%7Bservice%3D%22meteor-shower%22%7D&g0.tab=0&g0.stacked=0&g0.range_input=1h
2. **Meteor operator**: https://prometheus-portal-opf-monitoring.apps.zero.massopen.cloud/graph?g0.expr=%7Bservice%3D%22meteor-operator-controller-manager-metrics-service%22%7D&g0.tab=0&g0.stacked=0&g0.range_input=1h

**Comment by hemajv** [comment]
We also have the pipeline metrics: https://prometheus-portal-opf-monitoring.apps.zero.massopen.cloud/graph?g0.expr=%7Bservice%3D%22tekton-pipelines-controller%22%7D&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h
thanks to @harshad16 :tada:
