### ISSUE TITLE
Google Analytics data available externally

### ISSUE THREAD

**Issue by hemajv** [AICoE/meteor#60]
Now that we have GA setup for fetching metrics for the Meteor application (#50), we should also look into making this data available externally i.e. exporting the data and analyzing within notebooks for performing additional analysis such as consolidating data from different sources, correlation of metrics etc.

**Acceptance Criteria**

- [ ] Export GA metrics and have it stored in Ceph/Trino DB
- [ ] Notebook to programmatically access the data

**Comment by isabelizimm** [comment]
When doing some research into this, it seems like this is best achieved by using the [Google Analytics API](https://console.cloud.google.com/apis/library/analytics.googleapis.com?project=gentle-epoch-321920&folder=&organizationId=&supportedpurview=project). This service looks to be an add on, but there is some sort of trial basis as well. 

When planning for how to gather data, we could also use CSVs of historical data, rather than interacting with the API directly. This is a bit clunkier and will involve some sort of manual processes, but may also be appropriate for this use case.

CC: @hemajv @Shreyanand @aakankshaduggal
